// Code generated by MockGen. DO NOT EDIT.
// Source: cactus/internal/service/core (interfaces: PipelineService)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_pipeline_service.go cactus/internal/service/core PipelineService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "cactus/apps/core/internal/DTO"
	pipeline "cactus/apps/core/internal/service/pipeline"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPipelineService is a mock of PipelineService interface.
type MockPipelineService struct {
	ctrl     *gomock.Controller
	recorder *MockPipelineServiceMockRecorder
}

// MockPipelineServiceMockRecorder is the mock recorder for MockPipelineService.
type MockPipelineServiceMockRecorder struct {
	mock *MockPipelineService
}

// NewMockPipelineService creates a new mock instance.
func NewMockPipelineService(ctrl *gomock.Controller) *MockPipelineService {
	mock := &MockPipelineService{ctrl: ctrl}
	mock.recorder = &MockPipelineServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPipelineService) EXPECT() *MockPipelineServiceMockRecorder {
	return m.recorder
}

// CreatePipelineTX mocks base method.
func (m *MockPipelineService) CreatePipelineTX(ctx context.Context, storageTx pipeline.StorageTx, arg pipeline.CreatePipelineParams) ([]dto.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipelineTX", ctx, storageTx, arg)
	ret0, _ := ret[0].([]dto.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipelineTX indicates an expected call of CreatePipelineTX.
func (mr *MockPipelineServiceMockRecorder) CreatePipelineTX(ctx, storageTx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipelineTX", reflect.TypeOf((*MockPipelineService)(nil).CreatePipelineTX), ctx, storageTx, arg)
}
