// Code generated by MockGen. DO NOT EDIT.
// Source: cactus/internal/service/core (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_storage.go cactus/internal/service/core Storage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	db "github.com/zalberix/cactus/apps/core/storage/db"
	context "context"
	json "encoding/json"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockStorage) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockStorageMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockStorage)(nil).Commit))
}

// CreateFile mocks base method.
func (m *MockStorage) CreateFile(arg0 context.Context, arg1 db.CreateFileParams) (db.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFile", arg0, arg1)
	ret0, _ := ret[0].(db.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFile indicates an expected call of CreateFile.
func (mr *MockStorageMockRecorder) CreateFile(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFile", reflect.TypeOf((*MockStorage)(nil).CreateFile), arg0, arg1)
}

// CreateKindWorker mocks base method.
func (m *MockStorage) CreateKindWorker(arg0 context.Context, arg1 db.CreateKindWorkerParams) (db.KindWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKindWorker", arg0, arg1)
	ret0, _ := ret[0].(db.KindWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKindWorker indicates an expected call of CreateKindWorker.
func (mr *MockStorageMockRecorder) CreateKindWorker(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKindWorker", reflect.TypeOf((*MockStorage)(nil).CreateKindWorker), arg0, arg1)
}

// CreateMessage mocks base method.
func (m *MockStorage) CreateMessage(arg0 context.Context, arg1 db.CreateMessageParams) (db.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", arg0, arg1)
	ret0, _ := ret[0].(db.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockStorageMockRecorder) CreateMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockStorage)(nil).CreateMessage), arg0, arg1)
}

// CreateManifest mocks base method.
func (m *MockStorage) CreateManifest(arg0 context.Context, arg1 json.RawMessage) (db.Manifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateManifest", arg0, arg1)
	ret0, _ := ret[0].(db.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateManifest indicates an expected call of CreateManifest.
func (mr *MockStorageMockRecorder) CreateManifest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateManifest", reflect.TypeOf((*MockStorage)(nil).CreateManifest), arg0, arg1)
}

// CreatePipeline mocks base method.
func (m *MockStorage) CreatePipeline(arg0 context.Context, arg1 db.CreatePipelineParams) (db.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipeline", arg0, arg1)
	ret0, _ := ret[0].(db.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipeline indicates an expected call of CreatePipeline.
func (mr *MockStorageMockRecorder) CreatePipeline(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipeline", reflect.TypeOf((*MockStorage)(nil).CreatePipeline), arg0, arg1)
}

// CreatePipelineStep mocks base method.
func (m *MockStorage) CreatePipelineStep(arg0 context.Context, arg1 db.CreatePipelineStepParams) (db.PipelineStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipelineStep", arg0, arg1)
	ret0, _ := ret[0].(db.PipelineStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipelineStep indicates an expected call of CreatePipelineStep.
func (mr *MockStorageMockRecorder) CreatePipelineStep(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipelineStep", reflect.TypeOf((*MockStorage)(nil).CreatePipelineStep), arg0, arg1)
}

// CreateTypeWorker mocks base method.
func (m *MockStorage) CreateTypeWorker(arg0 context.Context, arg1 db.CreateTypeWorkerParams) (db.TypeWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTypeWorker", arg0, arg1)
	ret0, _ := ret[0].(db.TypeWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTypeWorker indicates an expected call of CreateTypeWorker.
func (mr *MockStorageMockRecorder) CreateTypeWorker(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTypeWorker", reflect.TypeOf((*MockStorage)(nil).CreateTypeWorker), arg0, arg1)
}

// CreateWorker mocks base method.
func (m *MockStorage) CreateWorker(arg0 context.Context, arg1 db.CreateWorkerParams) (db.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorker", arg0, arg1)
	ret0, _ := ret[0].(db.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorker indicates an expected call of CreateWorker.
func (mr *MockStorageMockRecorder) CreateWorker(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorker", reflect.TypeOf((*MockStorage)(nil).CreateWorker), arg0, arg1)
}

// GetFilePathByUUID mocks base method.
func (m *MockStorage) GetFilePathByUUID(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilePathByUUID", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilePathByUUID indicates an expected call of GetFilePathByUUID.
func (mr *MockStorageMockRecorder) GetFilePathByUUID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilePathByUUID", reflect.TypeOf((*MockStorage)(nil).GetFilePathByUUID), arg0, arg1)
}

// GetKindWokerByID mocks base method.
func (m *MockStorage) GetKindWokerByID(arg0 context.Context, arg1 int32) (db.KindWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKindWokerByID", arg0, arg1)
	ret0, _ := ret[0].(db.KindWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKindWokerByID indicates an expected call of GetKindWokerByID.
func (mr *MockStorageMockRecorder) GetKindWokerByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKindWokerByID", reflect.TypeOf((*MockStorage)(nil).GetKindWokerByID), arg0, arg1)
}

// GetKindWorkerBySlug mocks base method.
func (m *MockStorage) GetKindWorkerBySlug(arg0 context.Context, arg1 string) (db.KindWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKindWorkerBySlug", arg0, arg1)
	ret0, _ := ret[0].(db.KindWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKindWorkerBySlug indicates an expected call of GetKindWorkerBySlug.
func (mr *MockStorageMockRecorder) GetKindWorkerBySlug(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKindWorkerBySlug", reflect.TypeOf((*MockStorage)(nil).GetKindWorkerBySlug), arg0, arg1)
}

// GetMessagesBy mocks base method.
func (m *MockStorage) GetMessagesBy(arg0 context.Context, arg1 db.GetMessagesByParams) ([]db.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBy", arg0, arg1)
	ret0, _ := ret[0].([]db.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBy indicates an expected call of GetMessagesBy.
func (mr *MockStorageMockRecorder) GetMessagesBy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBy", reflect.TypeOf((*MockStorage)(nil).GetMessagesBy), arg0, arg1)
}

// GetPriorityBySlug mocks base method.
func (m *MockStorage) GetPriorityBySlug(arg0 context.Context, arg1 string) (db.Priority, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriorityBySlug", arg0, arg1)
	ret0, _ := ret[0].(db.Priority)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriorityBySlug indicates an expected call of GetPriorityBySlug.
func (mr *MockStorageMockRecorder) GetPriorityBySlug(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriorityBySlug", reflect.TypeOf((*MockStorage)(nil).GetPriorityBySlug), arg0, arg1)
}

// GetPriorityBySystemId mocks base method.
func (m *MockStorage) GetPriorityBySystemId(arg0 context.Context, arg1 int32) (db.GetPriorityBySystemIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriorityBySystemId", arg0, arg1)
	ret0, _ := ret[0].(db.GetPriorityBySystemIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriorityBySystemId indicates an expected call of GetPriorityBySystemId.
func (mr *MockStorageMockRecorder) GetPriorityBySystemId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriorityBySystemId", reflect.TypeOf((*MockStorage)(nil).GetPriorityBySystemId), arg0, arg1)
}

// GetStatusMessageByUUID mocks base method.
func (m *MockStorage) GetStatusMessageByUUID(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusMessageByUUID", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusMessageByUUID indicates an expected call of GetStatusMessageByUUID.
func (mr *MockStorageMockRecorder) GetStatusMessageByUUID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusMessageByUUID", reflect.TypeOf((*MockStorage)(nil).GetStatusMessageByUUID), arg0, arg1)
}

// GetSystemById mocks base method.
func (m *MockStorage) GetSystemById(arg0 context.Context, arg1 int32) (db.System, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemById", arg0, arg1)
	ret0, _ := ret[0].(db.System)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemById indicates an expected call of GetSystemById.
func (mr *MockStorageMockRecorder) GetSystemById(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemById", reflect.TypeOf((*MockStorage)(nil).GetSystemById), arg0, arg1)
}

// GetTokenByPublicToken mocks base method.
func (m *MockStorage) GetTokenByPublicToken(arg0 context.Context, arg1 string) (db.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByPublicToken", arg0, arg1)
	ret0, _ := ret[0].(db.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByPublicToken indicates an expected call of GetTokenByPublicToken.
func (mr *MockStorageMockRecorder) GetTokenByPublicToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByPublicToken", reflect.TypeOf((*MockStorage)(nil).GetTokenByPublicToken), arg0, arg1)
}

// GetTypeSlugWorkerByKindSlugWorker mocks base method.
func (m *MockStorage) GetTypeSlugWorkerByKindSlugWorker(ctx context.Context, slug string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTypeSlugWorkerByKindSlugWorker", ctx, slug)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTypeSlugWorkerByKindSlugWorker indicates an expected call of GetTypeSlugWorkerByKindSlugWorker.
func (mr *MockStorageMockRecorder) GetTypeSlugWorkerByKindSlugWorker(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTypeSlugWorkerByKindSlugWorker", reflect.TypeOf((*MockStorage)(nil).GetTypeSlugWorkerByKindSlugWorker), ctx, slug)
}

// GetTypeWorkerBySlug mocks base method.
func (m *MockStorage) GetTypeWorkerBySlug(arg0 context.Context, arg1 string) (db.TypeWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTypeWorkerBySlug", arg0, arg1)
	ret0, _ := ret[0].(db.TypeWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTypeWorkerBySlug indicates an expected call of GetTypeWorkerBySlug.
func (mr *MockStorageMockRecorder) GetTypeWorkerBySlug(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTypeWorkerBySlug", reflect.TypeOf((*MockStorage)(nil).GetTypeWorkerBySlug), arg0, arg1)
}

// GetTypeWorkers mocks base method.
func (m *MockStorage) GetTypeWorkers(arg0 context.Context) ([]db.TypeWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTypeWorkers", arg0)
	ret0, _ := ret[0].([]db.TypeWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTypeWorkers indicates an expected call of GetTypeWorkers.
func (mr *MockStorageMockRecorder) GetTypeWorkers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTypeWorkers", reflect.TypeOf((*MockStorage)(nil).GetTypeWorkers), arg0)
}

// GetWorkerByUUID mocks base method.
func (m *MockStorage) GetWorkerByUUID(arg0 context.Context, arg1 uuid.UUID) (db.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerByUUID", arg0, arg1)
	ret0, _ := ret[0].(db.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkerByUUID indicates an expected call of GetWorkerByUUID.
func (mr *MockStorageMockRecorder) GetWorkerByUUID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerByUUID", reflect.TypeOf((*MockStorage)(nil).GetWorkerByUUID), arg0, arg1)
}

// Rollback mocks base method.
func (m *MockStorage) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockStorageMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockStorage)(nil).Rollback))
}

// SetContext mocks base method.
func (m *MockStorage) SetContext(arg0 context.Context, arg1 any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetContext", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetContext indicates an expected call of SetContext.
func (mr *MockStorageMockRecorder) SetContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContext", reflect.TypeOf((*MockStorage)(nil).SetContext), arg0, arg1)
}
