// Code generated by MockGen. DO NOT EDIT.
// Source: cactus/internal/service/core (interfaces: Broker)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_broker.go cactus/internal/service/core Broker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	"github.com/zalberix/cactus/libs/pipeline"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBroker is a mock of Broker interface.
type MockBroker struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerMockRecorder
}

// MockBrokerMockRecorder is the mock recorder for MockBroker.
type MockBrokerMockRecorder struct {
	mock *MockBroker
}

// NewMockBroker creates a new mock instance.
func NewMockBroker(ctrl *gomock.Controller) *MockBroker {
	mock := &MockBroker{ctrl: ctrl}
	mock.recorder = &MockBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroker) EXPECT() *MockBrokerMockRecorder {
	return m.recorder
}

// AddMessageToQueue mocks base method.
func (m *MockBroker) AddMessageToQueue(arg0 context.Context, arg1 string, arg2 pipeline.MessageInQueue, arg3 pipeline.SystemInQueue, arg4 pipeline.PipelineInQueue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessageToQueue", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessageToQueue indicates an expected call of AddMessageToQueue.
func (mr *MockBrokerMockRecorder) AddMessageToQueue(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageToQueue", reflect.TypeOf((*MockBroker)(nil).AddMessageToQueue), arg0, arg1, arg2, arg3, arg4)
}

// EnsureStreamGroup mocks base method.
func (m *MockBroker) EnsureStreamGroup(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureStreamGroup", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureStreamGroup indicates an expected call of EnsureStreamGroup.
func (mr *MockBrokerMockRecorder) EnsureStreamGroup(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureStreamGroup", reflect.TypeOf((*MockBroker)(nil).EnsureStreamGroup), arg0, arg1, arg2)
}
