name: cactus-workers
services:
  smtp-worker:
    build:
      context: .
      dockerfile: docker/local/worker.Dockerfile
    restart: unless-stopped
    command: go run ./apps/smtp-worker/cmd/smtp-worker/
    volumes:
      - .:/app
      # smtp-worker загружает ./config/email.worker.yaml
      - ./configs/docker/email.worker.yaml:/app/config/email.worker.yaml
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    networks:
      - cactus-net

  telegram-worker:
    build:
      context: .
      dockerfile: docker/local/worker.Dockerfile
    restart: unless-stopped
    command: go run ./apps/telegram-worker/cmd/telegram-worker/
    volumes:
      - .:/app
      # telegram-worker загружает ./config/telegram.worker.yaml
      - ./configs/docker/telegram.worker.yaml:/app/config/telegram.worker.yaml
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    networks:
      - cactus-net

  telegram-bot:
    build:
      context: .
      dockerfile: docker/telegram-bot.Dockerfile
    restart: unless-stopped
    ports:
      - "8008:80"
    environment:
      - SERVICE_PORT=80
    volumes:
      - ./apps/telegram-bot/cmd/telegram-bot/subscriptions.db:/src/apps/telegram-bot/cmd/telegram-bot/subscriptions.db
    env_file:
      - ./apps/telegram-bot/cmd/telegram-bot/.env
    networks:
      - cactus-net

volumes:
  go-mod-cache:
    external: true
    name: cactus_go-mod-cache
  go-build-cache:
    external: true
    name: cactus_go-build-cache

networks:
  cactus-net:
    external: true
    name: cactus-net
