name: cactus

services:
  db:
    image: postgres:17.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./docker/assets/postgres:/var/lib/postgresql/data
    networks:
      - cactus-net

  nats:
    image: nats:2.10.11-scratch
    command: -js -m 8222 --config /etc/nats/nats.conf
    restart: unless-stopped
    volumes:
      - ./configs/nats.conf:/etc/nats/nats.conf:ro
      - ./docker/assets/nats:/data
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - cactus-net

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MH_STORAGE: "memory"
    networks:
      - cactus-net

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: s3admin
      RUSTFS_SECRET_KEY: s3admin
    volumes:
      - ./docker/assets/rustfs:/data
    networks:
      - cactus-net

volumes:
  go-mod-cache:
  go-build-cache:
  web-node-modules:

networks:
  cactus-net:
    driver: bridge
    name: cactus-net
