// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: file.sql

package db

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO file (
    message_id,
    title,
    "name",
    ext,
    url
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, message_id, title, name, ext, url
`

type CreateFileParams struct {
	MessageID int32  `json:"message_id"`
	Title     string `json:"title"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	Url       string `json:"url"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.MessageID,
		arg.Title,
		arg.Name,
		arg.Ext,
		arg.Url,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Title,
		&i.Name,
		&i.Ext,
		&i.Url,
	)
	return i, err
}

const getFilesByMessageID = `-- name: GetFilesByMessageID :many
SELECT id, message_id, title, name, ext, url FROM file
WHERE message_id = $1
`

func (q *Queries) GetFilesByMessageID(ctx context.Context, messageID int32) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFilesByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Title,
			&i.Name,
			&i.Ext,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
