// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: file.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO file (
    id_message, 
    title, 
    "path", 
    ext, 
    "uuid"
) VALUES ($1, $2, $3, $4, $5) 
RETURNING id_file, id_message, title, path, ext, uuid, create_at
`

type CreateFileParams struct {
	IDMessage int32     `json:"id_message"`
	Title     string    `json:"title"`
	Path      string    `json:"path"`
	Ext       string    `json:"ext"`
	Uuid      uuid.UUID `json:"uuid"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.IDMessage,
		arg.Title,
		arg.Path,
		arg.Ext,
		arg.Uuid,
	)
	var i File
	err := row.Scan(
		&i.IDFile,
		&i.IDMessage,
		&i.Title,
		&i.Path,
		&i.Ext,
		&i.Uuid,
		&i.CreateAt,
	)
	return i, err
}

const getFilePathByUUID = `-- name: GetFilePathByUUID :one
SELECT "path" FROM file
WHERE uuid = $1
LIMIT 1
`

func (q *Queries) GetFilePathByUUID(ctx context.Context, argUuid uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getFilePathByUUID, argUuid)
	var path string
	err := row.Scan(&path)
	return path, err
}
