// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: kind_worker.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const createKindWorker = `-- name: CreateKindWorker :one
INSERT INTO kind_worker (
    "name", 
    slug, 
    config_schema, 
    config
) VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, config_schema, config
`

type CreateKindWorkerParams struct {
	Name         string                `json:"name"`
	Slug         string                `json:"slug"`
	ConfigSchema json.RawMessage       `json:"config_schema"`
	Config       pqtype.NullRawMessage `json:"config"`
}

func (q *Queries) CreateKindWorker(ctx context.Context, arg CreateKindWorkerParams) (KindWorker, error) {
	row := q.db.QueryRowContext(ctx, createKindWorker,
		arg.Name,
		arg.Slug,
		arg.ConfigSchema,
		arg.Config,
	)
	var i KindWorker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ConfigSchema,
		&i.Config,
	)
	return i, err
}

const getKindWokerById = `-- name: GetKindWokerById :one
SELECT id, name, slug, config_schema, config 
FROM kind_worker kw
WHERE kw.id = $1
LIMIT 1
`

func (q *Queries) GetKindWokerById(ctx context.Context, id int32) (KindWorker, error) {
	row := q.db.QueryRowContext(ctx, getKindWokerById, id)
	var i KindWorker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ConfigSchema,
		&i.Config,
	)
	return i, err
}

const getKindWorkerBySlug = `-- name: GetKindWorkerBySlug :one
SELECT id, name, slug, config_schema, config 
FROM kind_worker kw
WHERE kw.slug = $1
LIMIT 1
`

func (q *Queries) GetKindWorkerBySlug(ctx context.Context, slug string) (KindWorker, error) {
	row := q.db.QueryRowContext(ctx, getKindWorkerBySlug, slug)
	var i KindWorker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ConfigSchema,
		&i.Config,
	)
	return i, err
}
