// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: message.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO message (
    system_id,
    manifest_id,
    "uuid",
    priority,
    value,
    send_at
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, system_id, manifest_id, uuid, priority, value, send_at, created_at, updated_at, deleted_at
`

type CreateMessageParams struct {
	SystemID   int32           `json:"system_id"`
	ManifestID int32           `json:"manifest_id"`
	Uuid       uuid.UUID       `json:"uuid"`
	Priority   int32           `json:"priority"`
	Value      json.RawMessage `json:"value"`
	SendAt     sql.NullTime    `json:"send_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.SystemID,
		arg.ManifestID,
		arg.Uuid,
		arg.Priority,
		arg.Value,
		arg.SendAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.ManifestID,
		&i.Uuid,
		&i.Priority,
		&i.Value,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageByUUID = `-- name: GetMessageByUUID :one
SELECT id, system_id, manifest_id, uuid, priority, value, send_at, created_at, updated_at, deleted_at FROM message
WHERE "uuid" = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetMessageByUUID(ctx context.Context, argUuid uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByUUID, argUuid)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SystemID,
		&i.ManifestID,
		&i.Uuid,
		&i.Priority,
		&i.Value,
		&i.SendAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessagesBySystemID = `-- name: GetMessagesBySystemID :many
SELECT id, system_id, manifest_id, uuid, priority, value, send_at, created_at, updated_at, deleted_at FROM message
WHERE system_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMessagesBySystemID(ctx context.Context, systemID int32) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesBySystemID, systemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.ManifestID,
			&i.Uuid,
			&i.Priority,
			&i.Value,
			&i.SendAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
