// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Message struct {
	ID         int32           `json:"id"`
	IDProcess  int32           `json:"id_process"`
	IDSystem   int32           `json:"id_system"`
	Uuid       uuid.UUID       `json:"uuid"`
	Value      json.RawMessage `json:"value"`
	IDPriority int32           `json:"id_priority"`
	SendLater  sql.NullTime    `json:"send_later"`
	CreateAt   time.Time       `json:"create_at"`
}

type Permission struct {
	ID          int32          `json:"id"`
	Description sql.NullString `json:"description"`
	Slug        string         `json:"slug"`
}

type PermissionRole struct {
	IDPermission int32 `json:"id_permission"`
	IDRole       int32 `json:"id_role"`
}

type Pipline struct {
	ID              int32        `json:"id"`
	IDPiplineStatus int32        `json:"id_pipline_status"`
	IDMessage       int32        `json:"id_message"`
	Step            int32        `json:"step"`
	Name            string       `json:"name"`
	TimeStart       sql.NullTime `json:"time_start"`
	TimeEnd         sql.NullTime `json:"time_end"`
}

type PiplineStatus struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Priority struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Weight int32  `json:"weight"`
	Slug   string `json:"slug"`
}

type Process struct {
	ID         int32                 `json:"id"`
	Name       string                `json:"name"`
	Slug       string                `json:"slug"`
	ToolsShema pqtype.NullRawMessage `json:"tools_shema"`
}

type ProcessClientTool struct {
	IDProcess int32                 `json:"id_process"`
	IDSystem  int32                 `json:"id_system"`
	Tools     pqtype.NullRawMessage `json:"tools"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type RoleUser struct {
	IDRole int32 `json:"id_role"`
	IDUser int32 `json:"id_user"`
}

type SystemClient struct {
	ID          int32          `json:"id"`
	CreateUser  sql.NullInt32  `json:"create_user"`
	IDPriority  int32          `json:"id_priority"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      bool           `json:"status"`
}

type Token struct {
	ID          int32  `json:"id"`
	IDSystem    int32  `json:"id_system"`
	IDProcess   int32  `json:"id_process"`
	Status      bool   `json:"status"`
	Token       string `json:"token"`
	SecretToken string `json:"secret_token"`
}

type User struct {
	ID                      int32        `json:"id"`
	Login                   string       `json:"login"`
	Email                   string       `json:"email"`
	Password                string       `json:"password"`
	ResetPasswordAfterLogin sql.NullBool `json:"reset_password_after_login"`
	CreateAt                sql.NullTime `json:"create_at"`
}

type Worker struct {
	ID        int32         `json:"id"`
	Name      string        `json:"name"`
	IDProcess sql.NullInt32 `json:"id_process"`
}
