// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type File struct {
	IDFile    int32     `json:"id_file"`
	IDMessage int32     `json:"id_message"`
	Title     string    `json:"title"`
	Path      string    `json:"path"`
	Ext       string    `json:"ext"`
	Uuid      uuid.UUID `json:"uuid"`
	CreateAt  time.Time `json:"create_at"`
}

type KindWorker struct {
	ID           int32                 `json:"id"`
	Name         string                `json:"name"`
	Slug         string                `json:"slug"`
	ConfigSchema pqtype.NullRawMessage `json:"config_schema"`
	Config       pqtype.NullRawMessage `json:"config"`
}

type KindWorkerSystem struct {
	IDSystem     int32 `json:"id_system"`
	IDKindWorker int32 `json:"id_kind_worker"`
}

type Message struct {
	ID           int32           `json:"id"`
	IDWorker     sql.NullInt32   `json:"id_worker"`
	IDTypeWorker int32           `json:"id_type_worker"`
	IDSystem     int32           `json:"id_system"`
	IDPriority   int32           `json:"id_priority"`
	Uuid         uuid.UUID       `json:"uuid"`
	Value        json.RawMessage `json:"value"`
	SendLater    sql.NullTime    `json:"send_later"`
	CreateAt     time.Time       `json:"create_at"`
}

type Permission struct {
	ID          int32          `json:"id"`
	Description sql.NullString `json:"description"`
	Slug        string         `json:"slug"`
}

type PermissionRole struct {
	IDPermission int32 `json:"id_permission"`
	IDRole       int32 `json:"id_role"`
}

type Pipeline struct {
	ID        int32        `json:"id"`
	IDMessage int32        `json:"id_message"`
	Status    string       `json:"status"`
	Step      int32        `json:"step"`
	Name      string       `json:"name"`
	TimeStart sql.NullTime `json:"time_start"`
	TimeEnd   sql.NullTime `json:"time_end"`
}

type Priority struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Weight int32  `json:"weight"`
	Slug   string `json:"slug"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type RoleUser struct {
	IDRole int32 `json:"id_role"`
	IDUser int32 `json:"id_user"`
}

type System struct {
	ID          int32          `json:"id"`
	CreateUser  sql.NullInt32  `json:"create_user"`
	IDPriority  int32          `json:"id_priority"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	IsActive    bool           `json:"is_active"`
}

type Token struct {
	IDSystem     int32  `json:"id_system"`
	IDKindWorker int32  `json:"id_kind_worker"`
	IsActive     bool   `json:"is_active"`
	PublicToken  string `json:"public_token"`
	SecretToken  string `json:"secret_token"`
}

type TypeWorker struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type User struct {
	ID                      int32        `json:"id"`
	Fio                     string       `json:"fio"`
	Login                   string       `json:"login"`
	Email                   string       `json:"email"`
	Password                string       `json:"password"`
	ResetPasswordAfterLogin sql.NullBool `json:"reset_password_after_login"`
	CreateAt                sql.NullTime `json:"create_at"`
}

type Worker struct {
	ID           int32 `json:"id"`
	IsActive     bool  `json:"is_active"`
	IDTypeWorker int32 `json:"id_type_worker"`
	IDKindWorker int32 `json:"id_kind_worker"`
}
