// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pipeline_step_status.sql

package db

import (
	"context"
)

const createPipelineStepStatus = `-- name: CreatePipelineStepStatus :one
INSERT INTO pipeline_step_status ("name", slug)
VALUES ($1, $2)
RETURNING id, name, slug
`

type CreatePipelineStepStatusParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreatePipelineStepStatus(ctx context.Context, arg CreatePipelineStepStatusParams) (PipelineStepStatus, error) {
	row := q.db.QueryRowContext(ctx, createPipelineStepStatus, arg.Name, arg.Slug)
	var i PipelineStepStatus
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const getPipelineStepStatusBySlug = `-- name: GetPipelineStepStatusBySlug :one
SELECT id, name, slug FROM pipeline_step_status
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetPipelineStepStatusBySlug(ctx context.Context, slug string) (PipelineStepStatus, error) {
	row := q.db.QueryRowContext(ctx, getPipelineStepStatusBySlug, slug)
	var i PipelineStepStatus
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}
