// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pipeline.sql

package db

import (
	"context"
	"database/sql"
)

const createPipelineStep = `-- name: CreatePipelineStep :one
INSERT INTO pipeline (
    id_message, 
    status,
    step, 
    "name", 
    time_start, 
    time_end
) VALUES ($1, $2, $3, $4, $5, $6) 
RETURNING id, id_message, status, step, name, time_start, time_end
`

type CreatePipelineStepParams struct {
	IDMessage int32        `json:"id_message"`
	Status    string       `json:"status"`
	Step      int32        `json:"step"`
	Name      string       `json:"name"`
	TimeStart sql.NullTime `json:"time_start"`
	TimeEnd   sql.NullTime `json:"time_end"`
}

func (q *Queries) CreatePipelineStep(ctx context.Context, arg CreatePipelineStepParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, createPipelineStep,
		arg.IDMessage,
		arg.Status,
		arg.Step,
		arg.Name,
		arg.TimeStart,
		arg.TimeEnd,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.IDMessage,
		&i.Status,
		&i.Step,
		&i.Name,
		&i.TimeStart,
		&i.TimeEnd,
	)
	return i, err
}
