// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pipeline_step.sql

package db

import (
	"context"
	"database/sql"
)

const createPipelineStep = `-- name: CreatePipelineStep :one
INSERT INTO pipeline_step (
    pipeline_id,
    worker_id,
    channel_id,
    step,
    time_start,
    time_end,
    pipeline_step_status_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, pipeline_id, worker_id, channel_id, step, time_start, time_end, created_at, updated_at, deleted_at, pipeline_step_status_id
`

type CreatePipelineStepParams struct {
	PipelineID           int32         `json:"pipeline_id"`
	WorkerID             sql.NullInt32 `json:"worker_id"`
	ChannelID            int32         `json:"channel_id"`
	Step                 int32         `json:"step"`
	TimeStart            sql.NullTime  `json:"time_start"`
	TimeEnd              sql.NullTime  `json:"time_end"`
	PipelineStepStatusID int32         `json:"pipeline_step_status_id"`
}

func (q *Queries) CreatePipelineStep(ctx context.Context, arg CreatePipelineStepParams) (PipelineStep, error) {
	row := q.db.QueryRowContext(ctx, createPipelineStep,
		arg.PipelineID,
		arg.WorkerID,
		arg.ChannelID,
		arg.Step,
		arg.TimeStart,
		arg.TimeEnd,
		arg.PipelineStepStatusID,
	)
	var i PipelineStep
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.WorkerID,
		&i.ChannelID,
		&i.Step,
		&i.TimeStart,
		&i.TimeEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PipelineStepStatusID,
	)
	return i, err
}

const getPipelineStepByPipelineIDAndStep = `-- name: GetPipelineStepByPipelineIDAndStep :one
SELECT id, pipeline_id, worker_id, channel_id, step, time_start, time_end, created_at, updated_at, deleted_at, pipeline_step_status_id FROM pipeline_step
WHERE pipeline_id = $1 AND step = $2 AND deleted_at IS NULL
`

type GetPipelineStepByPipelineIDAndStepParams struct {
	PipelineID int32 `json:"pipeline_id"`
	Step       int32 `json:"step"`
}

func (q *Queries) GetPipelineStepByPipelineIDAndStep(ctx context.Context, arg GetPipelineStepByPipelineIDAndStepParams) (PipelineStep, error) {
	row := q.db.QueryRowContext(ctx, getPipelineStepByPipelineIDAndStep, arg.PipelineID, arg.Step)
	var i PipelineStep
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.WorkerID,
		&i.ChannelID,
		&i.Step,
		&i.TimeStart,
		&i.TimeEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PipelineStepStatusID,
	)
	return i, err
}

const getPipelineStepsByPipelineID = `-- name: GetPipelineStepsByPipelineID :many
SELECT id, pipeline_id, worker_id, channel_id, step, time_start, time_end, created_at, updated_at, deleted_at, pipeline_step_status_id FROM pipeline_step
WHERE pipeline_id = $1 AND deleted_at IS NULL
ORDER BY step
`

func (q *Queries) GetPipelineStepsByPipelineID(ctx context.Context, pipelineID int32) ([]PipelineStep, error) {
	rows, err := q.db.QueryContext(ctx, getPipelineStepsByPipelineID, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineStep
	for rows.Next() {
		var i PipelineStep
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.WorkerID,
			&i.ChannelID,
			&i.Step,
			&i.TimeStart,
			&i.TimeEnd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PipelineStepStatusID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipelineStepStatusAndWorker = `-- name: UpdatePipelineStepStatusAndWorker :one
UPDATE pipeline_step
SET pipeline_step_status_id = $2, worker_id = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, pipeline_id, worker_id, channel_id, step, time_start, time_end, created_at, updated_at, deleted_at, pipeline_step_status_id
`

type UpdatePipelineStepStatusAndWorkerParams struct {
	ID                   int32         `json:"id"`
	PipelineStepStatusID int32         `json:"pipeline_step_status_id"`
	WorkerID             sql.NullInt32 `json:"worker_id"`
}

func (q *Queries) UpdatePipelineStepStatusAndWorker(ctx context.Context, arg UpdatePipelineStepStatusAndWorkerParams) (PipelineStep, error) {
	row := q.db.QueryRowContext(ctx, updatePipelineStepStatusAndWorker, arg.ID, arg.PipelineStepStatusID, arg.WorkerID)
	var i PipelineStep
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.WorkerID,
		&i.ChannelID,
		&i.Step,
		&i.TimeStart,
		&i.TimeEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PipelineStepStatusID,
	)
	return i, err
}
