// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: process.sql

package db

import (
	"context"
)

const getProcessBySlug = `-- name: GetProcessBySlug :one
SELECT id, name, slug, tools_shema FROM process
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetProcessBySlug(ctx context.Context, slug string) (Process, error) {
	row := q.db.QueryRowContext(ctx, getProcessBySlug, slug)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ToolsShema,
	)
	return i, err
}
