// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: system.sql

package db

import (
	"context"
)

const getSystemIdByToken = `-- name: GetSystemIdByToken :one
SELECT sc.id
FROM system_client sc
INNER JOIN "token" t ON t.id_system = sc.id
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetSystemIdByToken(ctx context.Context, token string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getSystemIdByToken, token)
	var id int32
	err := row.Scan(&id)
	return id, err
}
