// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: token.sql

package db

import (
	"context"
)

const createToken = `-- name: CreateToken :one
INSERT INTO "token" (
    id_system, 
    id_kind_worker, 
    is_active, 
    public_token, 
    secret_token
) VALUES ($1, $2, $3, $4, $5)
RETURNING id_system, id_kind_worker, is_active, public_token, secret_token
`

type CreateTokenParams struct {
	IDSystem     int32  `json:"id_system"`
	IDKindWorker int32  `json:"id_kind_worker"`
	IsActive     bool   `json:"is_active"`
	PublicToken  string `json:"public_token"`
	SecretToken  string `json:"secret_token"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.IDSystem,
		arg.IDKindWorker,
		arg.IsActive,
		arg.PublicToken,
		arg.SecretToken,
	)
	var i Token
	err := row.Scan(
		&i.IDSystem,
		&i.IDKindWorker,
		&i.IsActive,
		&i.PublicToken,
		&i.SecretToken,
	)
	return i, err
}

const getTokenByPublicToken = `-- name: GetTokenByPublicToken :one
SELECT id_system, id_kind_worker, is_active, public_token, secret_token
FROM "token" t
WHERE public_token = $1
LIMIT 1
`

func (q *Queries) GetTokenByPublicToken(ctx context.Context, publicToken string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByPublicToken, publicToken)
	var i Token
	err := row.Scan(
		&i.IDSystem,
		&i.IDKindWorker,
		&i.IsActive,
		&i.PublicToken,
		&i.SecretToken,
	)
	return i, err
}
