// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: type_worker.sql

package db

import (
	"context"
)

const getTypeWorkerBySlug = `-- name: GetTypeWorkerBySlug :one
SELECT id, name, slug FROM type_worker
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetTypeWorkerBySlug(ctx context.Context, slug string) (TypeWorker, error) {
	row := q.db.QueryRowContext(ctx, getTypeWorkerBySlug, slug)
	var i TypeWorker
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}
