// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
    fio, 
    login, 
    email, 
    "password", 
    reset_password_after_login, 
    create_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, fio, login, email, password, reset_password_after_login, create_at
`

type CreateUserParams struct {
	Fio                     string       `json:"fio"`
	Login                   string       `json:"login"`
	Email                   string       `json:"email"`
	Password                string       `json:"password"`
	ResetPasswordAfterLogin sql.NullBool `json:"reset_password_after_login"`
	CreateAt                sql.NullTime `json:"create_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Fio,
		arg.Login,
		arg.Email,
		arg.Password,
		arg.ResetPasswordAfterLogin,
		arg.CreateAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fio,
		&i.Login,
		&i.Email,
		&i.Password,
		&i.ResetPasswordAfterLogin,
		&i.CreateAt,
	)
	return i, err
}
