// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: worker.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO worker ("uuid", is_active, id_type_worker, id_kind_worker) 
VALUES($1, $2, $3, $4)
RETURNING id, uuid, is_active, id_type_worker, id_kind_worker
`

type CreateWorkerParams struct {
	Uuid         uuid.UUID `json:"uuid"`
	IsActive     bool      `json:"is_active"`
	IDTypeWorker int32     `json:"id_type_worker"`
	IDKindWorker int32     `json:"id_kind_worker"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker,
		arg.Uuid,
		arg.IsActive,
		arg.IDTypeWorker,
		arg.IDKindWorker,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.IsActive,
		&i.IDTypeWorker,
		&i.IDKindWorker,
	)
	return i, err
}

const getWorkerByUUID = `-- name: GetWorkerByUUID :one
SELECT id, uuid, is_active, id_type_worker, id_kind_worker 
FROM worker w
WHERE w.uuid = $1
LIMIT 1
`

func (q *Queries) GetWorkerByUUID(ctx context.Context, argUuid uuid.UUID) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByUUID, argUuid)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.IsActive,
		&i.IDTypeWorker,
		&i.IDKindWorker,
	)
	return i, err
}
