// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: worker.sql

package db

import (
	"context"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO worker (channel_id, config_id, is_active)
VALUES ($1, $2, $3)
RETURNING id, channel_id, config_id, is_active
`

type CreateWorkerParams struct {
	ChannelID int32 `json:"channel_id"`
	ConfigID  int32 `json:"config_id"`
	IsActive  bool  `json:"is_active"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker, arg.ChannelID, arg.ConfigID, arg.IsActive)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ConfigID,
		&i.IsActive,
	)
	return i, err
}

const getChannelSlugByWorkerID = `-- name: GetChannelSlugByWorkerID :one
SELECT c.slug
FROM worker w
JOIN channel c ON c.id = w.channel_id
WHERE w.id = $1
`

func (q *Queries) GetChannelSlugByWorkerID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getChannelSlugByWorkerID, id)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const getWorkerByID = `-- name: GetWorkerByID :one
SELECT id, channel_id, config_id, is_active FROM worker
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetWorkerByID(ctx context.Context, id int32) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorkerByID, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ConfigID,
		&i.IsActive,
	)
	return i, err
}
