// Code generated by MockGen. DO NOT EDIT.
// Source: cactus/internal/service/core (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_storage.go cactus/internal/service/core Storage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	db "cactus/internal/storage/db"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockStorage) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockStorageMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockStorage)(nil).Commit))
}

// CreateFile mocks base method.
func (m *MockStorage) CreateFile(ctx context.Context, arg db.CreateFileParams) (db.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFile", ctx, arg)
	ret0, _ := ret[0].(db.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFile indicates an expected call of CreateFile.
func (mr *MockStorageMockRecorder) CreateFile(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFile", reflect.TypeOf((*MockStorage)(nil).CreateFile), ctx, arg)
}

// CreateKindWorker mocks base method.
func (m *MockStorage) CreateKindWorker(ctx context.Context, arg db.CreateKindWorkerParams) (db.KindWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKindWorker", ctx, arg)
	ret0, _ := ret[0].(db.KindWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKindWorker indicates an expected call of CreateKindWorker.
func (mr *MockStorageMockRecorder) CreateKindWorker(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKindWorker", reflect.TypeOf((*MockStorage)(nil).CreateKindWorker), ctx, arg)
}

// CreateMessage mocks base method.
func (m *MockStorage) CreateMessage(ctx context.Context, arg db.CreateMessageParams) (db.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, arg)
	ret0, _ := ret[0].(db.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockStorageMockRecorder) CreateMessage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockStorage)(nil).CreateMessage), ctx, arg)
}

// CreatePipelineStep mocks base method.
func (m *MockStorage) CreatePipelineStep(ctx context.Context, arg db.CreatePipelineStepParams) (db.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipelineStep", ctx, arg)
	ret0, _ := ret[0].(db.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipelineStep indicates an expected call of CreatePipelineStep.
func (mr *MockStorageMockRecorder) CreatePipelineStep(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipelineStep", reflect.TypeOf((*MockStorage)(nil).CreatePipelineStep), ctx, arg)
}

// CreateTypeWorker mocks base method.
func (m *MockStorage) CreateTypeWorker(ctx context.Context, arg db.CreateTypeWorkerParams) (db.TypeWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTypeWorker", ctx, arg)
	ret0, _ := ret[0].(db.TypeWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTypeWorker indicates an expected call of CreateTypeWorker.
func (mr *MockStorageMockRecorder) CreateTypeWorker(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTypeWorker", reflect.TypeOf((*MockStorage)(nil).CreateTypeWorker), ctx, arg)
}

// CreateWorker mocks base method.
func (m *MockStorage) CreateWorker(ctx context.Context, arg db.CreateWorkerParams) (db.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorker", ctx, arg)
	ret0, _ := ret[0].(db.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWorker indicates an expected call of CreateWorker.
func (mr *MockStorageMockRecorder) CreateWorker(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorker", reflect.TypeOf((*MockStorage)(nil).CreateWorker), ctx, arg)
}

// GetFilePathByUUID mocks base method.
func (m *MockStorage) GetFilePathByUUID(ctx context.Context, argUUID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilePathByUUID", ctx, argUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilePathByUUID indicates an expected call of GetFilePathByUUID.
func (mr *MockStorageMockRecorder) GetFilePathByUUID(ctx, argUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilePathByUUID", reflect.TypeOf((*MockStorage)(nil).GetFilePathByUUID), ctx, argUUID)
}

// GetKindWokerByID mocks base method.
func (m *MockStorage) GetKindWokerByID(ctx context.Context, id int32) (db.KindWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKindWokerByID", ctx, id)
	ret0, _ := ret[0].(db.KindWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKindWokerByID indicates an expected call of GetKindWokerByID.
func (mr *MockStorageMockRecorder) GetKindWokerByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKindWokerByID", reflect.TypeOf((*MockStorage)(nil).GetKindWokerByID), ctx, id)
}

// GetKindWorkerBySlug mocks base method.
func (m *MockStorage) GetKindWorkerBySlug(ctx context.Context, slug string) (db.KindWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKindWorkerBySlug", ctx, slug)
	ret0, _ := ret[0].(db.KindWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKindWorkerBySlug indicates an expected call of GetKindWorkerBySlug.
func (mr *MockStorageMockRecorder) GetKindWorkerBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKindWorkerBySlug", reflect.TypeOf((*MockStorage)(nil).GetKindWorkerBySlug), ctx, slug)
}

// GetMessagesBy mocks base method.
func (m *MockStorage) GetMessagesBy(ctx context.Context, arg db.GetMessagesByParams) ([]db.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBy", ctx, arg)
	ret0, _ := ret[0].([]db.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBy indicates an expected call of GetMessagesBy.
func (mr *MockStorageMockRecorder) GetMessagesBy(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBy", reflect.TypeOf((*MockStorage)(nil).GetMessagesBy), ctx, arg)
}

// GetPriorityBySlug mocks base method.
func (m *MockStorage) GetPriorityBySlug(ctx context.Context, slug string) (db.Priority, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriorityBySlug", ctx, slug)
	ret0, _ := ret[0].(db.Priority)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriorityBySlug indicates an expected call of GetPriorityBySlug.
func (mr *MockStorageMockRecorder) GetPriorityBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriorityBySlug", reflect.TypeOf((*MockStorage)(nil).GetPriorityBySlug), ctx, slug)
}

// GetPriorityBySystemId mocks base method.
func (m *MockStorage) GetPriorityBySystemId(ctx context.Context, id int32) (db.GetPriorityBySystemIdRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriorityBySystemId", ctx, id)
	ret0, _ := ret[0].(db.GetPriorityBySystemIdRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriorityBySystemId indicates an expected call of GetPriorityBySystemId.
func (mr *MockStorageMockRecorder) GetPriorityBySystemId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriorityBySystemId", reflect.TypeOf((*MockStorage)(nil).GetPriorityBySystemId), ctx, id)
}

// GetStatusMessageByUUID mocks base method.
func (m *MockStorage) GetStatusMessageByUUID(ctx context.Context, argUUID uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusMessageByUUID", ctx, argUUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusMessageByUUID indicates an expected call of GetStatusMessageByUUID.
func (mr *MockStorageMockRecorder) GetStatusMessageByUUID(ctx, argUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusMessageByUUID", reflect.TypeOf((*MockStorage)(nil).GetStatusMessageByUUID), ctx, argUUID)
}

// GetSystemById mocks base method.
func (m *MockStorage) GetSystemById(ctx context.Context, id int32) (db.System, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemById", ctx, id)
	ret0, _ := ret[0].(db.System)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemById indicates an expected call of GetSystemById.
func (mr *MockStorageMockRecorder) GetSystemById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemById", reflect.TypeOf((*MockStorage)(nil).GetSystemById), ctx, id)
}

// GetTokenByPublicToken mocks base method.
func (m *MockStorage) GetTokenByPublicToken(ctx context.Context, publicToken string) (db.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByPublicToken", ctx, publicToken)
	ret0, _ := ret[0].(db.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByPublicToken indicates an expected call of GetTokenByPublicToken.
func (mr *MockStorageMockRecorder) GetTokenByPublicToken(ctx, publicToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByPublicToken", reflect.TypeOf((*MockStorage)(nil).GetTokenByPublicToken), ctx, publicToken)
}

// GetTypeWorkerBySlug mocks base method.
func (m *MockStorage) GetTypeWorkerBySlug(ctx context.Context, slug string) (db.TypeWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTypeWorkerBySlug", ctx, slug)
	ret0, _ := ret[0].(db.TypeWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTypeWorkerBySlug indicates an expected call of GetTypeWorkerBySlug.
func (mr *MockStorageMockRecorder) GetTypeWorkerBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTypeWorkerBySlug", reflect.TypeOf((*MockStorage)(nil).GetTypeWorkerBySlug), ctx, slug)
}

// GetTypeWorkers mocks base method.
func (m *MockStorage) GetTypeWorkers(ctx context.Context) ([]db.TypeWorker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTypeWorkers", ctx)
	ret0, _ := ret[0].([]db.TypeWorker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTypeWorkers indicates an expected call of GetTypeWorkers.
func (mr *MockStorageMockRecorder) GetTypeWorkers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTypeWorkers", reflect.TypeOf((*MockStorage)(nil).GetTypeWorkers), ctx)
}

// GetWorkerByUUID mocks base method.
func (m *MockStorage) GetWorkerByUUID(ctx context.Context, argUUID uuid.UUID) (db.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerByUUID", ctx, argUUID)
	ret0, _ := ret[0].(db.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkerByUUID indicates an expected call of GetWorkerByUUID.
func (mr *MockStorageMockRecorder) GetWorkerByUUID(ctx, argUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerByUUID", reflect.TypeOf((*MockStorage)(nil).GetWorkerByUUID), ctx, argUUID)
}

// Rollback mocks base method.
func (m *MockStorage) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockStorageMockRecorder) Rollback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockStorage)(nil).Rollback))
}

// SetContext mocks base method.
func (m *MockStorage) SetContext(ctx context.Context, db any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetContext", ctx, db)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetContext indicates an expected call of SetContext.
func (mr *MockStorageMockRecorder) SetContext(ctx, db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContext", reflect.TypeOf((*MockStorage)(nil).SetContext), ctx, db)
}
