// Code generated by MockGen. DO NOT EDIT.
// Source: cactus/internal/service/core (interfaces: Plugins)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_plugins.go cactus/internal/service/core Plugins
//

// Package mocks is a generated GoMock package.
package mocks

import (
	plugin "cactus/internal/plugin"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlugins is a mock of Plugins interface.
type MockPlugins struct {
	ctrl     *gomock.Controller
	recorder *MockPluginsMockRecorder
	isgomock struct{}
}

// MockPluginsMockRecorder is the mock recorder for MockPlugins.
type MockPluginsMockRecorder struct {
	mock *MockPlugins
}

// NewMockPlugins creates a new mock instance.
func NewMockPlugins(ctrl *gomock.Controller) *MockPlugins {
	mock := &MockPlugins{ctrl: ctrl}
	mock.recorder = &MockPluginsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlugins) EXPECT() *MockPluginsMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockPlugins) Add(slug string, plugin plugin.Plugin) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", slug, plugin)
}

// Add indicates an expected call of Add.
func (mr *MockPluginsMockRecorder) Add(slug, plugin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockPlugins)(nil).Add), slug, plugin)
}

// Delete mocks base method.
func (m *MockPlugins) Delete(slug string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", slug)
}

// Delete indicates an expected call of Delete.
func (mr *MockPluginsMockRecorder) Delete(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPlugins)(nil).Delete), slug)
}

// Get mocks base method.
func (m *MockPlugins) Get(slug string) (plugin.Plugin, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", slug)
	ret0, _ := ret[0].(plugin.Plugin)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPluginsMockRecorder) Get(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPlugins)(nil).Get), slug)
}
