// Code generated by MockGen. DO NOT EDIT.
// Source: cactus/internal/service/core (interfaces: Broker)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_broker.go cactus/internal/service/core Broker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "cactus/internal/DTO"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBroker is a mock of Broker interface.
type MockBroker struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerMockRecorder
	isgomock struct{}
}

// MockBrokerMockRecorder is the mock recorder for MockBroker.
type MockBrokerMockRecorder struct {
	mock *MockBroker
}

// NewMockBroker creates a new mock instance.
func NewMockBroker(ctrl *gomock.Controller) *MockBroker {
	mock := &MockBroker{ctrl: ctrl}
	mock.recorder = &MockBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroker) EXPECT() *MockBrokerMockRecorder {
	return m.recorder
}

// AddMessageToQueue mocks base method.
func (m *MockBroker) AddMessageToQueue(ctx context.Context, streamName string, messageDTO dto.MessageValueInMessageQueue, systemDTO dto.SystemValueInMessageQueue, pipelineDTO dto.PipelineValueInMessageQueue) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessageToQueue", ctx, streamName, messageDTO, systemDTO, pipelineDTO)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessageToQueue indicates an expected call of AddMessageToQueue.
func (mr *MockBrokerMockRecorder) AddMessageToQueue(ctx, streamName, messageDTO, systemDTO, pipelineDTO any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageToQueue", reflect.TypeOf((*MockBroker)(nil).AddMessageToQueue), ctx, streamName, messageDTO, systemDTO, pipelineDTO)
}

// EnsureStreamGroup mocks base method.
func (m *MockBroker) EnsureStreamGroup(ctx context.Context, streamName, groupName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureStreamGroup", ctx, streamName, groupName)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureStreamGroup indicates an expected call of EnsureStreamGroup.
func (mr *MockBrokerMockRecorder) EnsureStreamGroup(ctx, streamName, groupName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureStreamGroup", reflect.TypeOf((*MockBroker)(nil).EnsureStreamGroup), ctx, streamName, groupName)
}
