// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: channel.sql

package db

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channel (slug, "name")
VALUES ( $1, $2)
RETURNING id, name, slug
`

type CreateChannelParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, arg.Slug, arg.Name)
	var i Channel
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const getChannelBySlug = `-- name: GetChannelBySlug :one
SELECT id, name, slug FROM channel
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetChannelBySlug(ctx context.Context, slug string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelBySlug, slug)
	var i Channel
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const getChannels = `-- name: GetChannels :many
SELECT id, name, slug FROM channel
`

func (q *Queries) GetChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
