// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: config.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const createConfig = `-- name: CreateConfig :one
INSERT INTO config (
    "name",
    config_schema,
    config
) VALUES ($1, $2, $3)
RETURNING id, name, config_schema, config
`

type CreateConfigParams struct {
	Name         string                `json:"name"`
	ConfigSchema json.RawMessage       `json:"config_schema"`
	Config       pqtype.NullRawMessage `json:"config"`
}

func (q *Queries) CreateConfig(ctx context.Context, arg CreateConfigParams) (Config, error) {
	row := q.db.QueryRowContext(ctx, createConfig, arg.Name, arg.ConfigSchema, arg.Config)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConfigSchema,
		&i.Config,
	)
	return i, err
}

const getConfigByID = `-- name: GetConfigByID :one
SELECT id, name, config_schema, config FROM config
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetConfigByID(ctx context.Context, id int32) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfigByID, id)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ConfigSchema,
		&i.Config,
	)
	return i, err
}
