// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: manifest.sql

package db

import (
	"context"
	"encoding/json"
)

const createManifest = `-- name: CreateManifest :one
INSERT INTO manifest (value)
VALUES ($1)
RETURNING id, value
`

func (q *Queries) CreateManifest(ctx context.Context, value json.RawMessage) (Manifest, error) {
	row := q.db.QueryRowContext(ctx, createManifest, value)
	var i Manifest
	err := row.Scan(&i.ID, &i.Value)
	return i, err
}

const getManifestByID = `-- name: GetManifestByID :one
SELECT id, value FROM manifest
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetManifestByID(ctx context.Context, id int32) (Manifest, error) {
	row := q.db.QueryRowContext(ctx, getManifestByID, id)
	var i Manifest
	err := row.Scan(&i.ID, &i.Value)
	return i, err
}
