// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Channel struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type ChannelSystem struct {
	SystemID  int32 `json:"system_id"`
	ChannelID int32 `json:"channel_id"`
}

type Config struct {
	ID           int32                 `json:"id"`
	Name         string                `json:"name"`
	ConfigSchema json.RawMessage       `json:"config_schema"`
	Config       pqtype.NullRawMessage `json:"config"`
}

type File struct {
	ID        int32  `json:"id"`
	MessageID int32  `json:"message_id"`
	Title     string `json:"title"`
	Name      string `json:"name"`
	Ext       string `json:"ext"`
	Url       string `json:"url"`
}

type Manifest struct {
	ID    int32           `json:"id"`
	Value json.RawMessage `json:"value"`
}

type Message struct {
	ID         int32           `json:"id"`
	SystemID   int32           `json:"system_id"`
	ManifestID int32           `json:"manifest_id"`
	Uuid       uuid.UUID       `json:"uuid"`
	Priority   int32           `json:"priority"`
	Value      json.RawMessage `json:"value"`
	SendAt     sql.NullTime    `json:"send_at"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  sql.NullTime    `json:"updated_at"`
	DeletedAt  sql.NullTime    `json:"deleted_at"`
}

type Permission struct {
	ID   int32  `json:"id"`
	Slug string `json:"slug"`
}

type PermissionRole struct {
	PermissionID int32 `json:"permission_id"`
	RoleID       int32 `json:"role_id"`
}

type Pipeline struct {
	ID               int32         `json:"id"`
	MessageID        int32         `json:"message_id"`
	ParentPipelineID sql.NullInt32 `json:"parent_pipeline_id"`
	CreatedAt        sql.NullTime  `json:"created_at"`
	UpdatedAt        sql.NullTime  `json:"updated_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
}

type PipelineStep struct {
	ID                   int32         `json:"id"`
	PipelineID           int32         `json:"pipeline_id"`
	WorkerID             sql.NullInt32 `json:"worker_id"`
	ChannelID            int32         `json:"channel_id"`
	Step                 int32         `json:"step"`
	TimeStart            sql.NullTime  `json:"time_start"`
	TimeEnd              sql.NullTime  `json:"time_end"`
	CreatedAt            sql.NullTime  `json:"created_at"`
	UpdatedAt            sql.NullTime  `json:"updated_at"`
	DeletedAt            sql.NullTime  `json:"deleted_at"`
	PipelineStepStatusID int32         `json:"pipeline_step_status_id"`
}

type PipelineStepStatus struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type Role struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type RoleUser struct {
	RoleID int32 `json:"role_id"`
	UserID int32 `json:"user_id"`
}

type System struct {
	ID            int32          `json:"id"`
	UserCreatorID sql.NullInt32  `json:"user_creator_id"`
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	IsActive      bool           `json:"is_active"`
	Priority      int32          `json:"priority"`
	PublicToken   sql.NullString `json:"public_token"`
	PrivateToken  sql.NullString `json:"private_token"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
}

type User struct {
	ID                      int32          `json:"id"`
	LastName                string         `json:"last_name"`
	FirstName               string         `json:"first_name"`
	Patronymic              sql.NullString `json:"patronymic"`
	Email                   string         `json:"email"`
	Password                string         `json:"password"`
	ResetPasswordAfterLogin sql.NullBool   `json:"reset_password_after_login"`
	CreatedAt               sql.NullTime   `json:"created_at"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
	DeletedAt               sql.NullTime   `json:"deleted_at"`
}

type Worker struct {
	ID        int32 `json:"id"`
	ChannelID int32 `json:"channel_id"`
	ConfigID  int32 `json:"config_id"`
	IsActive  bool  `json:"is_active"`
}
