// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pipeline.sql

package db

import (
	"context"
	"database/sql"
)

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO pipeline (
    message_id,
    parent_pipeline_id
) VALUES ($1, $2)
RETURNING id, message_id, parent_pipeline_id, created_at, updated_at, deleted_at
`

type CreatePipelineParams struct {
	MessageID        int32         `json:"message_id"`
	ParentPipelineID sql.NullInt32 `json:"parent_pipeline_id"`
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, createPipeline, arg.MessageID, arg.ParentPipelineID)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ParentPipelineID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPipelineByID = `-- name: GetPipelineByID :one
SELECT id, message_id, parent_pipeline_id, created_at, updated_at, deleted_at FROM pipeline
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPipelineByID(ctx context.Context, id int32) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, getPipelineByID, id)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ParentPipelineID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPipelinesByMessageID = `-- name: GetPipelinesByMessageID :many
SELECT id, message_id, parent_pipeline_id, created_at, updated_at, deleted_at FROM pipeline
WHERE message_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPipelinesByMessageID(ctx context.Context, messageID int32) ([]Pipeline, error) {
	rows, err := q.db.QueryContext(ctx, getPipelinesByMessageID, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pipeline
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ParentPipelineID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
