// Code generated by MockGen. DO NOT EDIT.
// Source: cactus/internal/service/pipeline (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_storage.go cactus/internal/service/pipeline Storage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	db "github.com/zalberix/cactus/apps/core/storage/db"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetIDPipelineByUUIDMessageAndStep mocks base method.
func (m *MockStorage) GetIDPipelineByUUIDMessageAndStep(arg0 context.Context, arg1 db.GetIDPipelineByUUIDMessageAndStepParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDPipelineByUUIDMessageAndStep", arg0, arg1)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDPipelineByUUIDMessageAndStep indicates an expected call of GetIDPipelineByUUIDMessageAndStep.
func (mr *MockStorageMockRecorder) GetIDPipelineByUUIDMessageAndStep(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDPipelineByUUIDMessageAndStep", reflect.TypeOf((*MockStorage)(nil).GetIDPipelineByUUIDMessageAndStep), arg0, arg1)
}

// GetWorkerByUUID mocks base method.
func (m *MockStorage) GetWorkerByUUID(arg0 context.Context, arg1 uuid.UUID) (db.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerByUUID", arg0, arg1)
	ret0, _ := ret[0].(db.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkerByUUID indicates an expected call of GetWorkerByUUID.
func (mr *MockStorageMockRecorder) GetWorkerByUUID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerByUUID", reflect.TypeOf((*MockStorage)(nil).GetWorkerByUUID), arg0, arg1)
}

// UpdatePipelineStatusAndWorkerByID mocks base method.
func (m *MockStorage) UpdatePipelineStatusAndWorkerByID(arg0 context.Context, arg1 db.UpdatePipelineStatusAndWorkerByIDParams) (db.PipelineStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineStatusAndWorkerByID", arg0, arg1)
	ret0, _ := ret[0].(db.PipelineStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePipelineStatusAndWorkerByID indicates an expected call of UpdatePipelineStatusAndWorkerByID.
func (mr *MockStorageMockRecorder) UpdatePipelineStatusAndWorkerByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineStatusAndWorkerByID", reflect.TypeOf((*MockStorage)(nil).UpdatePipelineStatusAndWorkerByID), arg0, arg1)
}
