// Code generated by MockGen. DO NOT EDIT.
// Source: cactus/internal/service/pipeline (interfaces: StorageTx)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_storage_tx.go cactus/internal/service/pipeline StorageTx
//

// Package mocks is a generated GoMock package.
package mocks

import (
	db "cactus/apps/core/storage/db"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageTx is a mock of StorageTx interface.
type MockStorageTx struct {
	ctrl     *gomock.Controller
	recorder *MockStorageTxMockRecorder
}

// MockStorageTxMockRecorder is the mock recorder for MockStorageTx.
type MockStorageTxMockRecorder struct {
	mock *MockStorageTx
}

// NewMockStorageTx creates a new mock instance.
func NewMockStorageTx(ctrl *gomock.Controller) *MockStorageTx {
	mock := &MockStorageTx{ctrl: ctrl}
	mock.recorder = &MockStorageTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageTx) EXPECT() *MockStorageTxMockRecorder {
	return m.recorder
}

// CreatePipeline mocks base method.
func (m *MockStorageTx) CreatePipeline(ctx context.Context, arg db.CreatePipelineParams) (db.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipeline", ctx, arg)
	ret0, _ := ret[0].(db.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipeline indicates an expected call of CreatePipeline.
func (mr *MockStorageTxMockRecorder) CreatePipeline(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipeline", reflect.TypeOf((*MockStorageTx)(nil).CreatePipeline), ctx, arg)
}

// CreatePipelineStep mocks base method.
func (m *MockStorageTx) CreatePipelineStep(ctx context.Context, arg db.CreatePipelineStepParams) (db.PipelineStep, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePipelineStep", ctx, arg)
	ret0, _ := ret[0].(db.PipelineStep)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePipelineStep indicates an expected call of CreatePipelineStep.
func (mr *MockStorageTxMockRecorder) CreatePipelineStep(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePipelineStep", reflect.TypeOf((*MockStorageTx)(nil).CreatePipelineStep), ctx, arg)
}
