// Code generated by MockGen. DO NOT EDIT.
// Source: cactus/internal/plugin (interfaces: Plugin)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_plugin.go cactus/internal/plugin Plugin
//

// Package mocks is a generated GoMock package.
package mocks

import (
	plugin "github.com/zalberix/cactus/apps/core/internal/plugin"
	pipeline "github.com/zalberix/cactus/libs/pipeline"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPlugin is a mock of Plugin interface.
type MockPlugin struct {
	ctrl     *gomock.Controller
	recorder *MockPluginMockRecorder
	isgomock struct{}
}

// MockPluginMockRecorder is the mock recorder for MockPlugin.
type MockPluginMockRecorder struct {
	mock *MockPlugin
}

// NewMockPlugin creates a new mock instance.
func NewMockPlugin(ctrl *gomock.Controller) *MockPlugin {
	mock := &MockPlugin{ctrl: ctrl}
	mock.recorder = &MockPluginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlugin) EXPECT() *MockPluginMockRecorder {
	return m.recorder
}

// ExtendPipeline mocks base method.
func (m *MockPlugin) ExtendPipeline(arg0 []pipeline.Step) ([]pipeline.Step, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendPipeline", arg0)
	ret0, _ := ret[0].([]pipeline.Step)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtendPipeline indicates an expected call of ExtendPipeline.
func (mr *MockPluginMockRecorder) ExtendPipeline(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendPipeline", reflect.TypeOf((*MockPlugin)(nil).ExtendPipeline), arg0)
}

// GetSchema mocks base method.
func (m *MockPlugin) GetSchema() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSchema")
	ret0, _ := ret[0].(any)
	return ret0
}

// GetSchema indicates an expected call of GetSchema.
func (mr *MockPluginMockRecorder) GetSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSchema", reflect.TypeOf((*MockPlugin)(nil).GetSchema))
}

// New mocks base method.
func (m *MockPlugin) New() plugin.Plugin {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(plugin.Plugin)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockPluginMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockPlugin)(nil).New))
}
