// Code generated by MockGen. DO NOT EDIT.
// Source: cactus/internal/service/pipeline (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_storage.go cactus/internal/service/pipeline Storage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	db "cactus/internal/storage/db"
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetIdPipelineByUUIDMessageAndStep mocks base method.
func (m *MockStorage) GetIdPipelineByUUIDMessageAndStep(ctx context.Context, arg db.GetIdPipelineByUUIDMessageAndStepParams) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdPipelineByUUIDMessageAndStep", ctx, arg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdPipelineByUUIDMessageAndStep indicates an expected call of GetIdPipelineByUUIDMessageAndStep.
func (mr *MockStorageMockRecorder) GetIdPipelineByUUIDMessageAndStep(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdPipelineByUUIDMessageAndStep", reflect.TypeOf((*MockStorage)(nil).GetIdPipelineByUUIDMessageAndStep), ctx, arg)
}

// GetWorkerByUUID mocks base method.
func (m *MockStorage) GetWorkerByUUID(ctx context.Context, argUUID uuid.UUID) (db.Worker, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkerByUUID", ctx, argUUID)
	ret0, _ := ret[0].(db.Worker)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkerByUUID indicates an expected call of GetWorkerByUUID.
func (mr *MockStorageMockRecorder) GetWorkerByUUID(ctx, argUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkerByUUID", reflect.TypeOf((*MockStorage)(nil).GetWorkerByUUID), ctx, argUUID)
}

// UpdatePipelineStatusAndWorkerByID mocks base method.
func (m *MockStorage) UpdatePipelineStatusAndWorkerByID(ctx context.Context, arg db.UpdatePipelineStatusAndWorkerByIDParams) (db.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePipelineStatusAndWorkerByID", ctx, arg)
	ret0, _ := ret[0].(db.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePipelineStatusAndWorkerByID indicates an expected call of UpdatePipelineStatusAndWorkerByID.
func (mr *MockStorageMockRecorder) UpdatePipelineStatusAndWorkerByID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePipelineStatusAndWorkerByID", reflect.TypeOf((*MockStorage)(nil).UpdatePipelineStatusAndWorkerByID), ctx, arg)
}
